Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,39 +1,22 @@
-# Build JAVA applications using Apache Maven (http://maven.apache.org)
-# For docker image tags see https://hub.docker.com/_/maven/
-#
-# This template will build and test your projects
-# * Caches downloaded dependencies and plugins between invocation.
-# * Verify but don't deploy merge requests.
-# * Deploy built artifacts from master branch only.
 stages:
   - test
   - deploy
   - visualize
 
 include:
-   - template: Code-Quality.gitlab-ci.yml
-   - template: Jobs/SAST.gitlab-ci.yml
+  - template: Code-Quality.gitlab-ci.yml
+  - template: Jobs/SAST.gitlab-ci.yml
 
 variables:
-  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
-  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
   MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
-  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
-  # when running from the command line.
-  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
   MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
 
-# This template uses jdk8 for verifying and deploying images
-image: maven:3.3.9-jdk-8
-
-# Cache downloaded dependencies and plugins between builds.
-# To keep cache across branches add 'key: "$CI_JOB_NAME"'
 cache:
+  key: "$CI_JOB_NAME"
   paths:
     - .m2/repository
 
-# For merge requests do not `deploy` but only run `verify`.
-# See https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
+# Template for verification jobs
 .verify: &verify
   stage: test
   script:
@@ -42,65 +25,54 @@ cache:
     when: always
     reports:
       junit:
-        - GraphicsViewCore/target/surefire-reports/TEST-*.xml
-        - GraphicsViewCore/target/failsafe-reports/TEST-*.xml
-        - GeoGraphicsView/target/surefire-reports/TEST-*.xml
-        - GeoGraphicsView/target/failsafe-reports/TEST-*.xml
-        - GeotoolsAdapter/target/surefire-reports/TEST-*.xml
-        - GeotoolsAdapter/target/failsafe-reports/TEST-*.xml
+        - "**/target/surefire-reports/TEST-*.xml"
+        - "**/target/failsafe-reports/TEST-*.xml"
     paths:
-      - GraphicsViewCore/target/site/jacoco/jacoco.xml
-      - GeoGraphicsView/target/site/jacoco/jacoco.xml
-      - GeotoolsAdapter/target/site/jacoco/jacoco.xml
+      - "**/target/site/jacoco/jacoco.xml"
 
-
-# Verify merge requests using JDK8
+# Verify with JDK 8
 verify:jdk8:
-  stage: test
+  image: maven:3.8.7-jdk-8
   <<: *verify
 
-# To deploy packages from CI, create a ci_settings.xml file
-# For deploying packages to GitLab's Maven Repository: See https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for more details.
-# Please note: The GitLab Maven Repository is currently only available in GitLab Premium / Ultimate.
-# For `master` branch run `mvn deploy` automatically.
+# Verify with JDK 21
+verify:jdk21:
+  image: maven:3.9.4-jdk-21
+  <<: *verify
+
+# Deploy with JDK 8
 deploy:jdk8.gitlab:
+  image: maven:3.8.7-jdk-8
   stage: deploy
   needs: ["verify:jdk8"]
   script:
-    - if [ ! -f ci_settings.xml ];
-        then echo "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for instructions.";
-      fi
+    - if [ ! -f ci_settings.xml ]; then echo "CI settings missing! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for instructions."; exit 1; fi
     - 'mvn $MAVEN_CLI_OPTS -Pgitlab deploy -s ci_settings.xml'
-  only: 
+  only:
     - tags
     - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
 
-    
-# Deploy to 'Repository' Project
-deploy:jdk8.gitlab.repository:
+# Deploy with JDK 21
+deploy:jdk21.gitlab:
+  image: maven:3.9.4-jdk-21
   stage: deploy
-  needs: ["verify:jdk8"]
+  needs: ["verify:jdk21"]
   script:
-    - if [ ! -f ci_settings.xml ];
-        then echo "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for instructions.";
-      fi
-    - 'mvn $MAVEN_CLI_OPTS -Pgitlab-snapshot deploy -s ci_settings.xml'
-  only: 
+    - if [ ! -f ci_settings.xml ]; then echo "CI settings missing! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for instructions."; exit 1; fi
+    - 'mvn $MAVEN_CLI_OPTS -Pgitlab deploy -s ci_settings.xml'
+  only:
+    - tags
     - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
 
-
+# Coverage job
 coverage:
-  # Must be in a stage later than test-jdk11's stage.
-  # The `visualize` stage does not exist by default.
-  # Please define it first, or choose an existing stage like `deploy`.
   stage: visualize
   image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
   script:
-    # convert report from jacoco to cobertura, using relative project path
-    - python /opt/cover2cover.py GraphicsViewCore/target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/GraphicsViewCore/src/main/java/ > GraphicsViewCore/target/site/cobertura.xml
-  needs: ["verify:jdk8"]
+    - python /opt/cover2cover.py "**/target/site/jacoco/jacoco.xml" $CI_PROJECT_DIR/src/main/java/ > "**/target/site/cobertura.xml"
+  needs: ["verify:jdk8", "verify:jdk21"]
   artifacts:
     reports:
       coverage_report:
         coverage_format: cobertura
-        path: GraphicsViewCore/target/site/cobertura.xml
+        path: "**/target/site/cobertura.xml"
